matrix:
  - name: Text Files
    aspell:
      lang: en
    dictionary:
      wordcodes:
        - en
      encoding: utf-8
      wordlists:
        - .wordlist.txt
    sources:
      - "**/*.txt"
      - "**/*.md"